"""big change

Revision ID: 2a08dca7fca0
Revises: fe48486e8178
Create Date: 2022-09-21 23:24:34.089081

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "2a08dca7fca0"
down_revision = "fe48486e8178"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_trx_status_id", table_name="trx_status")
    op.drop_table("trx_status")
    op.create_index(op.f("ix_profiles_pubkey"), "profiles", ["pubkey"], unique=False)
    op.create_index(op.f("ix_sent_msgs_message_id"), "sent_msgs", ["message_id"], unique=False)
    op.add_column("trxs", sa.Column("is_sent", sa.Boolean(), nullable=True))
    op.create_index(op.f("ix_trxs_is_sent"), "trxs", ["is_sent"], unique=False)
    op.create_index(op.f("ix_trxs_timestamp"), "trxs", ["timestamp"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trxs_timestamp"), table_name="trxs")
    op.drop_index(op.f("ix_trxs_is_sent"), table_name="trxs")
    op.drop_column("trxs", "is_sent")
    op.drop_index(op.f("ix_sent_msgs_message_id"), table_name="sent_msgs")
    op.drop_index(op.f("ix_profiles_pubkey"), table_name="profiles")
    op.create_table(
        "trx_status",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("trx_id", sa.VARCHAR(length=36), nullable=True),
        sa.Column("user_id", sa.VARCHAR(length=36), nullable=True),
        sa.Column("created_at", sa.VARCHAR(), nullable=True),
        sa.Column("updated_at", sa.VARCHAR(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_trx_status_id", "trx_status", ["id"], unique=False)
    # ### end Alembic commands ###
